@echo off
echo Starting bridge...
start cmd /k "cd /d print_bridge && node bridge.js"

echo Starting worker...
start cmd /k "cd /d print_bridge && node worker.js"

echo Starting reverb...
start cmd /k "php artisan reverb:start"

echo All services started...
