@echo off
echo Starting bridge...
start cmd /k "cd /d print_bridge && node bridge.js"

echo Starting worker...
start cmd /k "cd /d print_bridge && node worker.js"

echo Starting reverb...
start cmd /k "php artisan reverb:start --host=0.0.0.0 --port=8080"

echo Starting server...
start cmd /k "php artisan serve"

echo Starting Cloudflared tunnel...
start cmd /k "cd /d C:\ && cloudflared tunnel run campagna-pos"

echo All services started...
